name: slither analysis

on:
  push:
    paths:
      - '**'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add repo to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Set up Node
      uses: actions/setup-node@v4

    - name: Install pnpm
      run: npm install --global pnpm

    - name: Restore PNPM Package Cache
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: pnpm-packages-v3-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Copy foundry from Docker container
      run: |
        container_id=$(docker create onthertech/titan-ci-builder:latest)
        mkdir -p $HOME/bin
        docker cp $container_id:/usr/local/bin/cast $HOME/bin/
        docker cp $container_id:/usr/local/bin/anvil $HOME/bin/
        docker cp $container_id:/usr/local/bin/forge $HOME/bin/
        docker rm $container_id

    - name: Set permissions_add PATH
      run: |
        chmod +x $HOME/bin/*
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: pnpm install

    - name: Build the contracts
      run: |
        cd packages/tokamak/contracts-bedrock
        forge build --build-info --skip '*/test/**' '*/scripts/**'
        cd ../..

    - name: Save PNPM Package Cache
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: pnpm-packages-v4-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Run Slither
      uses: crytic/slither-action@v0.3.1
      with:
        target: packages/tokamak/contracts-bedrock
        slither-config: packages/tokamak/contracts-bedrock/slither.config.json
        fail-on: config
        slither-version: dev-triage-db
        slither-args: --triage-database packages/tokamak/contracts-bedrock/slither.db.json
        ignore-compile: true
