name: slither analysis

on:
  push:
    paths:
      - '**'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Set up Node
      uses: actions/setup-node@v4

    - name: Install pnpm
      run: npm install --global pnpm

    - name: Copy foundry from Docker container
      run: |
        container_id=$(docker create onthertech/titan-ci-builder:latest)
        mkdir -p $HOME/bin
        docker cp $container_id:/usr/local/bin/cast $HOME/bin/
        docker cp $container_id:/usr/local/bin/anvil $HOME/bin/
        docker cp $container_id:/usr/local/bin/forge $HOME/bin/
        docker rm $container_id

    - name: Set permissions_add PATH
      run: |
        chmod +x $HOME/bin/*
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Get pnpm cache directory path
      run: echo "PNPM_CACHE_DIR=$(pnpm config get cache)" >> $GITHUB_ENV

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ${{ env.PNPM_CACHE_DIR }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: pnpm install

    - name: Build the contracts
      run: |
        cd packages/tokamak/contracts-bedrock
        forge build --build-info --skip '*/test/**' '*/scripts/**'

    - name: Install solc-select and solc
      run: |
        pip3 install solc-select
        solc-select install 0.8.15
        solc-select use 0.8.15

    - name: Run Slither
      uses: crytic/slither-action@v0.3.1
      with:
        target: packages/tokamak/contracts-bedrock
        slither-config: packages/tokamak/contracts-bedrock/slither.config.json
        fail-on: config
        slither-version: dev-triage-db
        slither-args: --triage-database packages/tokamak/contracts-bedrock/slither.db.json
        ignore-compile: true
